"""Tests for server-side troubleshooting PDF rendering."""

from datetime import datetime, timedelta, timezone
from io import BytesIO

from pypdf import PdfReader

from c2ai.schemas.troubleshooting import (
    TroubleshootingEvent,
    TroubleshootingMetric,
    TroubleshootingMetricPoint,
    TroubleshootingReportRequest,
    TroubleshootingReportResponse,
    TroubleshootingWindow,
)
from c2ai.services.troubleshooting_pdf import _metric_value, build_troubleshooting_pdf


def test_pdf_metric_value_is_not_rounded():
    metric = TroubleshootingMetric(
        name="cpu_usage",
        label="CPU Usage",
        value=0.00476,
        unit="cores",
    )

    assert _metric_value(metric) == "0.00476 cores"


def test_pdf_contains_all_report_sections_and_multiple_pages():
    end = datetime(2026, 8, 23, 18, 46, tzinfo=timezone.utc)
    start = end - timedelta(hours=4)
    points = [
        TroubleshootingMetricPoint(
            timestamp=start + timedelta(minutes=index * 10),
            value=float(index),
        )
        for index in range(25)
    ]
    metrics = [
        TroubleshootingMetric(
            name=f"application_metric_{index}",
            label=f"Application Metric {index}",
            value=points[-1].value,
            points=points,
        )
        for index in range(4)
    ]
    events = [
        TroubleshootingEvent(
            id=f"event-{index}",
            timestamp=start + timedelta(minutes=index),
            source="kubernetes",
            severity="warning",
            resource=f"Pod/ada-{index}",
            event_type="Warning",
            reason="Unhealthy",
            message=(
                "Readiness probe failed while validating the application "
                f"container for event {index}."
            ),
        )
        for index in range(30)
    ]
    report = TroubleshootingReportResponse(
        generated_at=end,
        window=TroubleshootingWindow(start=start, end=end, hours=4),
        severity="warning",
        summary="The application has intermittent readiness failures.",
        most_likely_root_cause="A dependency is intermittently unavailable.",
        issue_started=events[0].timestamp,
        recommended_actions=[f"Recommended action {index}." for index in range(1, 5)],
        relevant_events=events[:4],
        cluster_events=events[:10],
        application_metrics=metrics,
        analyzed_log_lines=70,
        data_sources=["application", "kubernetes"],
    )
    request = TroubleshootingReportRequest(
        subdomain="amberd-test-release",
        deployment="ada",
        tier=1,
        status="Healthy",
        version="26.02.08",
        instance="release",
        client="test",
    )

    pdf = build_troubleshooting_pdf(report, request)

    assert pdf.startswith(b"%PDF-")
    assert len(pdf) > 5_000
    assert pdf.count(b"/Type /Page") >= 2

    reader = PdfReader(BytesIO(pdf))
    text = "\n".join(page.extract_text() or "" for page in reader.pages)
    assert "Application Logs" in text
    assert "Live Metrics" in text
    assert "Kubernetes Events" in text
    assert "AI Analysis" in text
    assert "LLM Analysis" not in text
    assert "Warning: The application has intermittent readiness failures." in text
    assert "RECOMMENDED ACTIONS" in text
    assert "APPLICATION METRICS FLAGGED BY AI (4)" in text
    assert "Generated by C2AI" in text
    assert "APPLICATION TROUBLESHOOTING REPORT" in text
    assert "AI APPLICATION TROUBLESHOOTING" not in text
    assert "C2AI" in text
    assert "ATHENA" not in text
    assert reader.metadata.author == "C2AI"
    assert reader.metadata.title == (
        "C2AI-application-troubleshooting-report-23-08-2026"
    )
    assert "Processing: Gathering data" not in text
    assert "Metrics selected by the analysis" not in text
    assert "All Kubernetes events included" not in text
    assert "Generated by Athena" not in text
